# Views are handlers that responds to requests from browsers and clients

# Handlers are written as Python Functions. 

# Each View Function is mapped to one or more request URLs.
from flask import render_template
from flask import url_for, redirect
# Import Request object to use
from flask import request
from app import app


# Map 2 Routes to the same Function. Can map a single route too.

@app.route('/prof')
def index():
	user = {'nickname': 'Ravi'}
	posts = [
		{
			'paper_id': '1',
			'paper_name': 'Vaiśesịka Graph Grammar (VGG) System',
			'paper_author': 'Rajesh Kumar TV, Navjyoti Singh',
			'paper_conference': 'Formal Ontology in Information Systems (FOIS)',
			'paper_date': '2018-09-17',
			'paper_reportno': 'IIIT/TR/2018/57',
			'info': 'Graph grammars, being a natural extension of string grammars as well as tree grammars, are highly expressive as well as powerful enough to capture the generative structure of a wide variety of scenarios - both simple and complex. But, unfortunately, we do not find many instances which leverage this power graph grammars provide us. Most of the graph grammars available so far are either toy grammars or limited to addressing highly specialized problems. In this paper, we present Vaiśes ika Graph Grammar (VGG) system, which is as wide as any graph grammar can get i.e., a grammar for reality as theorized in Vaiśes ika - the foundational ontology found in Indian analytic tradition. This paper extends the work presented in [1]. In [1], the generative as well as the interpretation rules of this system were presented. Here, apart from briefly discussing some of these rules, we also present a parser for such a system which makes it extremely powerful in terms of its ability to classify an input graph as a valid Vaiśes ̣ika graph or an invalid one which, in itself, is an immensely significant breakthrough for any ontological application. Apart from that, we also present a verification mechanism to verify the interpretations of graphs generated by the generative rules. This is done, at least statistically, if not formally, to give a statistical proof of the soundness of the system (that every generated graph has at least one Vaiśes ̣ika interpretation, and no useless graphs are generated.)'
		},
		{
			'paper_id': '2',
			'paper_name': 'Vaiśesịka Graph Grammar (VGG) System',
			'paper_author': 'Rajesh Kumar TV,Navjyoti Singh',
			'paper_conference': 'Formal Ontology in Information Systems (FOIS)',
			'paper_date': '2018-09-17',
			'paper_reportno': 'IIIT/TR/2018/57',
			'info': 'Graph grammars, being a natural extension of string grammars as well as tree grammars, are highly expressive as well as powerful enough to capture the generative structure of a wide variety of scenarios - both simple and complex. But, unfortunately, we do not find many instances which leverage this power graph grammars provide us. Most of the graph grammars available so far are either toy grammars or limited to addressing highly specialized problems. In this paper, we present Vaiśes ika Graph Grammar (VGG) system, which is as wide as any graph grammar can get i.e., a grammar for reality as theorized in Vaiśes ika - the foundational ontology found in Indian analytic tradition. This paper extends the work presented in [1]. In [1], the generative as well as the interpretation rules of this system were presented. Here, apart from briefly discussing some of these rules, we also present a parser for such a system which makes it extremely powerful in terms of its ability to classify an input graph as a valid Vaiśes ̣ika graph or an invalid one which, in itself, is an immensely significant breakthrough for any ontological application. Apart from that, we also present a verification mechanism to verify the interpretations of graphs generated by the generative rules. This is done, at least statistically, if not formally, to give a statistical proof of the soundness of the system (that every generated graph has at least one Vaiśes ̣ika interpretation, and no useless graphs are generated.)'
		},
		{
			'paper_id': '3',
			'paper_name': 'Vaiśesịka Graph Grammar (VGG) System',
			'paper_author': 'Rajesh Kumar TV,Navjyoti Singh',
			'paper_conference': 'Formal Ontology in Information Systems (FOIS)',
			'paper_date': '2018-09-17',
			'paper_reportno': 'IIIT/TR/2018/57',
			'info': 'Graph grammars, being a natural extension of string grammars as well as tree grammars, are highly expressive as well as powerful enough to capture the generative structure of a wide variety of scenarios - both simple and complex. But, unfortunately, we do not find many instances which leverage this power graph grammars provide us. Most of the graph grammars available so far are either toy grammars or limited to addressing highly specialized problems. In this paper, we present Vaiśes ika Graph Grammar (VGG) system, which is as wide as any graph grammar can get i.e., a grammar for reality as theorized in Vaiśes ika - the foundational ontology found in Indian analytic tradition. This paper extends the work presented in [1]. In [1], the generative as well as the interpretation rules of this system were presented. Here, apart from briefly discussing some of these rules, we also present a parser for such a system which makes it extremely powerful in terms of its ability to classify an input graph as a valid Vaiśes ̣ika graph or an invalid one which, in itself, is an immensely significant breakthrough for any ontological application. Apart from that, we also present a verification mechanism to verify the interpretations of graphs generated by the generative rules. This is done, at least statistically, if not formally, to give a statistical proof of the soundness of the system (that every generated graph has at least one Vaiśes ̣ika interpretation, and no useless graphs are generated.)'
		},
		{
			'paper_id': '4',
			'paper_name': 'Vaiśesịka Graph Grammar (VGG) System',
			'paper_author': 'Rajesh Kumar TV,Navjyoti Singh',
			'paper_conference': 'Formal Ontology in Information Systems (FOIS)',
			'paper_date': '2018-09-17',
			'paper_reportno': 'IIIT/TR/2018/57',
			'info': 'Graph grammars, being a natural extension of string grammars as well as tree grammars, are highly expressive as well as powerful enough to capture the generative structure of a wide variety of scenarios - both simple and complex. But, unfortunately, we do not find many instances which leverage this power graph grammars provide us. Most of the graph grammars available so far are either toy grammars or limited to addressing highly specialized problems. In this paper, we present Vaiśes ika Graph Grammar (VGG) system, which is as wide as any graph grammar can get i.e., a grammar for reality as theorized in Vaiśes ika - the foundational ontology found in Indian analytic tradition. This paper extends the work presented in [1]. In [1], the generative as well as the interpretation rules of this system were presented. Here, apart from briefly discussing some of these rules, we also present a parser for such a system which makes it extremely powerful in terms of its ability to classify an input graph as a valid Vaiśes ̣ika graph or an invalid one which, in itself, is an immensely significant breakthrough for any ontological application. Apart from that, we also present a verification mechanism to verify the interpretations of graphs generated by the generative rules. This is done, at least statistically, if not formally, to give a statistical proof of the soundness of the system (that every generated graph has at least one Vaiśes ̣ika interpretation, and no useless graphs are generated.)'
		},
		{
			'paper_id': '5',
			'paper_name': 'Vaiśesịka Graph Grammar (VGG) System',
			'paper_author': 'Rajesh Kumar TV,Navjyoti Singh',
			'paper_conference': 'Formal Ontology in Information Systems (FOIS)',
			'paper_date': '2018-09-17',
			'paper_reportno': 'IIIT/TR/2018/57',
			'info': 'Graph grammars, being a natural extension of string grammars as well as tree grammars, are highly expressive as well as powerful enough to capture the generative structure of a wide variety of scenarios - both simple and complex. But, unfortunately, we do not find many instances which leverage this power graph grammars provide us. Most of the graph grammars available so far are either toy grammars or limited to addressing highly specialized problems. In this paper, we present Vaiśes ika Graph Grammar (VGG) system, which is as wide as any graph grammar can get i.e., a grammar for reality as theorized in Vaiśes ika - the foundational ontology found in Indian analytic tradition. This paper extends the work presented in [1]. In [1], the generative as well as the interpretation rules of this system were presented. Here, apart from briefly discussing some of these rules, we also present a parser for such a system which makes it extremely powerful in terms of its ability to classify an input graph as a valid Vaiśes ̣ika graph or an invalid one which, in itself, is an immensely significant breakthrough for any ontological application. Apart from that, we also present a verification mechanism to verify the interpretations of graphs generated by the generative rules. This is done, at least statistically, if not formally, to give a statistical proof of the soundness of the system (that every generated graph has at least one Vaiśes ̣ika interpretation, and no useless graphs are generated.)'
		},
		{
			'paper_id': '6',
			'paper_name': 'Vaiśesịka Graph Grammar (VGG) System',
			'paper_author': 'Rajesh Kumar TV,Navjyoti Singh',
			'paper_conference': 'Formal Ontology in Information Systems (FOIS)',
			'paper_date': '2018-09-17',
			'paper_reportno': 'IIIT/TR/2018/57',
			'info': 'Graph grammars, being a natural extension of string grammars as well as tree grammars, are highly expressive as well as powerful enough to capture the generative structure of a wide variety of scenarios - both simple and complex. But, unfortunately, we do not find many instances which leverage this power graph grammars provide us. Most of the graph grammars available so far are either toy grammars or limited to addressing highly specialized problems. In this paper, we present Vaiśes ika Graph Grammar (VGG) system, which is as wide as any graph grammar can get i.e., a grammar for reality as theorized in Vaiśes ika - the foundational ontology found in Indian analytic tradition. This paper extends the work presented in [1]. In [1], the generative as well as the interpretation rules of this system were presented. Here, apart from briefly discussing some of these rules, we also present a parser for such a system which makes it extremely powerful in terms of its ability to classify an input graph as a valid Vaiśes ̣ika graph or an invalid one which, in itself, is an immensely significant breakthrough for any ontological application. Apart from that, we also present a verification mechanism to verify the interpretations of graphs generated by the generative rules. This is done, at least statistically, if not formally, to give a statistical proof of the soundness of the system (that every generated graph has at least one Vaiśes ̣ika interpretation, and no useless graphs are generated.)'
		},
		{
			'paper_id': '7',
			'paper_name': 'Vaiśesịka Graph Grammar (VGG) System',
			'paper_author': 'Rajesh Kumar TV,Navjyoti Singh',
			'paper_conference': 'Formal Ontology in Information Systems (FOIS)',
			'paper_date': '2018-09-17',
			'paper_reportno': 'IIIT/TR/2018/57',
			'info': 'Graph grammars, being a natural extension of string grammars as well as tree grammars, are highly expressive as well as powerful enough to capture the generative structure of a wide variety of scenarios - both simple and complex. But, unfortunately, we do not find many instances which leverage this power graph grammars provide us. Most of the graph grammars available so far are either toy grammars or limited to addressing highly specialized problems. In this paper, we present Vaiśes ika Graph Grammar (VGG) system, which is as wide as any graph grammar can get i.e., a grammar for reality as theorized in Vaiśes ika - the foundational ontology found in Indian analytic tradition. This paper extends the work presented in [1]. In [1], the generative as well as the interpretation rules of this system were presented. Here, apart from briefly discussing some of these rules, we also present a parser for such a system which makes it extremely powerful in terms of its ability to classify an input graph as a valid Vaiśes ̣ika graph or an invalid one which, in itself, is an immensely significant breakthrough for any ontological application. Apart from that, we also present a verification mechanism to verify the interpretations of graphs generated by the generative rules. This is done, at least statistically, if not formally, to give a statistical proof of the soundness of the system (that every generated graph has at least one Vaiśes ̣ika interpretation, and no useless graphs are generated.)'
		}	
	]
	return render_template('prof_page.html',title='Home',user=user,posts=posts)
	


# Simple returns a string to the client :-)